services:
  bookify.api:
    image: ${DOCKER_REGISTRY-}bookify-api
    container_name: bookify.api
    build:
      context: .
      dockerfile: src/Bookify.Api/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"

  bookify.db:
    image: postgres:latest
    container_name: bookify.db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bookify
    volumes:
      - ./.containers/bookify-db:/var/lib/postgresql/data
    ports:
      - "6543:6543"