services:
  bookify.api:
    image: ${DOCKER_REGISTRY-}bookify-api
    container_name: bookify.api
    build:
      context: .
      dockerfile: src/Bookify.Api/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      bookify.db:
        condition: service_healthy

  bookify.db:
    image: postgres:latest
    container_name: bookify.database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=bookify
    volumes:
      - ./.containers/bookify-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s